title: 'NetNote'
description: '只要学不死，就往死里学！'
local:
  lang: zh-CN
base: /
themeConfig:
  nav:
    -
      text: 开始项目
      link: /start/
    -
      text: 网络搭建
      link: /net/
    -
      text: 系统服务
      link: /serve/
    -
      text: GitHub
      link: https://github.com/Yue-plus/NetNote
  sidebar: 'auto'
repo: Yue-plus/NetNote
repoLabel: GitHub
editLinkText: GitHub