title: 'NetNote'
description: '只要学不死，就往死里学！'
local:
  lang: zh-CN
base: /
themeConfig:
  nav:
    -
      text: 开始项目
      link: /start/
    -
      text: 网络搭建
      items:
        -
          text: 网络基础
          link: /net/base/
        -
          text: 交换机配置
          link: /net/switch/
        -
          text: 路由器配置
          link: /net/router/
        -
          text: 无线配置
          link: /net/acap/
        -
          text: 安全配置
          link: /net/security/
        -
          text: 广域网配置
          link: /net/wan/
    -
      text: 系统服务
      items:
        - 
          text: 云平台与虚拟机
          link: /serve/VM/
        -
          text: Windows Server
          link: /serve/WS/
        -
          text: Linux
          link: /serve/Linux/
    -
      text: GitHub
      link: https://github.com/Yue-plus/NetNote
  sidebar: 'auto'
repo: Yue-plus/NetNote
repoLabel: GitHub
editLinkText: GitHub