title: 'NetNote'
description: '只要学不死，就往死里学！'
locales:
  '/':
    lang: 'zh-CN'
base: /
themeConfig:
  nav:
    -
      text: 起步
      items: 
        -
          text: 开始项目
          link: /start/start.html
        -
          text: GitHub 使用方法
          link: /start/github.html
        -
          text: Markdown 语法
          link: /start/markdown.html
    -
      text: 编程
      items:
        -
          text: Web 前端
          link: /coding/Web/
        -
          text: Java
          link: /coding/Java/
    -
      text: 网络搭建
      items:
        -
          text: 网络基础
          link: /net/base/
        -
          text: 交换机配置
          link: /net/switch/
        -
          text: 路由器配置
          link: /net/router/
        -
          text: 无线配置
          link: /net/acap/
        -
          text: 安全配置
          link: /net/security/
        -
          text: 广域网配置
          link: /net/wan/
    -
      text: 系统服务
      items:
        - 
          text: 云平台与虚拟机
          link: /serve/VM/
        -
          text: Windows Server
          link: /serve/WS/
        -
          text: Linux
          link: /serve/Linux/
    -
      text: GitHub
      link: https://github.com/Yue-plus/NetNote
  sidebar:
    '/start/':
      - 'start'
      - 'github'
      - 'markdown'
    '/coding/':
      - 'Web/'
      - 'Java/'
    '/net/':
      - 'base/'
      - 'switch/'
      - 'router/'
      - 'acap/'
      - 'security/'
      - 'wan/'
    '/serve/VM/':
      - 'Cloud/'
      - 'VMware'
    '/serve/WS/':
      - 'ActiveDirectoryDomain'
      - 'DFS'
      - 'NLB'
      - 'FailoverCluster'
    '/serve/Linux/':
      - '01-Base/'
      - '02-Chrony/'
      - '03-NFS/'
      - '04-MariaDB/'
      - '05-Apache/'
      - '06-Tomcat/'
      - '07-Samba/'
      - '08-NIS/'
      - '09-Postfix/'
      - '10-Pacemaker/'
  smoothScroll: true
  sidebarDepth: 2
repo: 'https://github.com/Yue-plus/NetNote'
repoLabel: '查看源码'